services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://dunyo_user:${POSTGRES_PASSWORD}@db:5432/dunyo_db
      DEBUG: "false"

  frontend:
    build: ./client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
