"""add branch table and employee branch_id

Revision ID: 058cc91bfc57
Revises: e24b86286417
Create Date: 2026-06-07 17:18:56.073026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058cc91bfc57'
down_revision: Union[str, Sequence[str], None] = 'e24b86286417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), server_default='150', nullable=False),
    sa.Column('leader_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['leaders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('branch_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_employees_branch_id', 'employees', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_branch_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'branch_id')
    op.drop_table('branches')
    # ### end Alembic commands ###
