"""add shift_number employee and delete attendance

Revision ID: 3a520cea80d3
Revises: b26425065529
Create Date: 2026-05-29 22:13:09.654456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a520cea80d3'
down_revision: Union[str, Sequence[str], None] = 'b26425065529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'shift_number')
    op.add_column('employees', sa.Column('shift_number', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('employees', 'default_shift')
    op.drop_column('employees', 'monthly_salary')
    op.add_column('salary_histories', sa.Column('bonus', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_histories', 'bonus')
    op.add_column('employees', sa.Column('monthly_salary', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('default_shift', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'shift_number')
    op.add_column('attendances', sa.Column('shift_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
