"""add is_active employee

Revision ID: 9ccf6d36bb82
Revises: 93e67f1bc8a9
Create Date: 2026-05-29 16:06:00.835136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccf6d36bb82'
down_revision: Union[str, Sequence[str], None] = '93e67f1bc8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_active')
    # ### end Alembic commands ###
