"""s

Revision ID: d7c19ccb4119
Revises: f5c0ad7c3e26
Create Date: 2026-05-30 19:27:49.281771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c19ccb4119'
down_revision: Union[str, Sequence[str], None] = 'f5c0ad7c3e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'notes')
    # ### end Alembic commands ###
