"""add shift_number employee and delete attendance

Revision ID: f5c0ad7c3e26
Revises: 3a520cea80d3
Create Date: 2026-05-29 22:21:35.896832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c0ad7c3e26'
down_revision: Union[str, Sequence[str], None] = '3a520cea80d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
